usecaseDiagram
    actor "Funcionário" as F
    actor "Administrador" as A

    %% Administrador herda permissões de Funcionário
    A --|> F

    package "Gestão de Frota e Clientes" {
        usecase "Cadastrar/Editar Veículos" as UC1
        usecase "Cadastrar/Editar Clientes" as UC2
        usecase "Consultar Histórico Veículo" as UC19
        usecase "Busca Avançada" as UC17
    }

    package "Operacional (Reservas e Locações)" {
        usecase "Gerenciar Reservas" as UC3
        usecase "Realizar Retirada (Check-in)" as UC4a
        usecase "Realizar Devolução (Check-out/Combustível)" as UC4b
        usecase "Gerar/Assinar Contrato Digital" as UC13
        usecase "Realizar Checklist/Fotos" as UC20
        usecase "Visualizar Dashboard Operacional" as UC16
    }

    package "Manutenção e Sinistros" {
        usecase "Registrar Manutenção" as UC5
        usecase "Registrar Sinistro/Seguro" as UC12
    }

    package "Administrativo e Financeiro" {
        usecase "Gerar Relatórios Gerenciais/Exportar" as UC6
        usecase "Gerenciar Usuários e Permissões" as UC7
        usecase "Consultar Logs de Auditoria" as UC8
        usecase "Configurar Taxas e Tarifas" as UC11
        usecase "Gerenciar Multas e Infrações" as UC15
        usecase "Receber Alertas de Documentos Vencidos" as UC18
    }

    %% Conexões do Funcionário
    F --> UC1
    F --> UC2
    F --> UC3
    F --> UC4a
    F --> UC4b
    F --> UC16
    F --> UC5
    F --> UC12
    F --> UC13
    F --> UC17
    F --> UC19
    F --> UC20

    %% Conexões Exclusivas do Administrador
    A --> UC6
    A --> UC7
    A --> UC8
    A --> UC11
    A --> UC15
    A --> UC18
